AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ENV:
    Type: String
    Default: PROD
  RoleName:
    Type: String
    Default: ClamAV-Malware-Scanner_CDK-Deploy
    Description: >-
      Name of Role used by CloudFormation, to Deploy a stack for
      ClamAV-Malware-Scanner
Resources:
  DeployRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: 'sts:AssumeRole'
      RoleName: !Ref RoleName
      Path: /
      Policies:
        - PolicyName: deploy-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              # - Sid: PassRoleForInitiator
              #   Effect: Allow
              #   Resource:
              #     - "*"
              #     # - !Sub "arn:${AWS::Partition}:sts::${AWS::AccountId}:assumed-role/cdk-*"
              #   Action:
              #     - 'iam:PassRole'
              - Sid: CloudFormationActions
                Effect: Allow
                Resource:
                  - !Sub "arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:stack*"
                  - !Sub "arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:changeSet*"
                Action:
                  - 'cloudformation:Create*'
                  - 'cloudformation:Update*'
                  - 'cloudformation:Delete*'
                  - 'cloudformation:Stop*'
                  - 'cloudformation:RollbackStack'
                  - 'cloudformation:CancelUpdateStack'
                  - 'cloudformation:ExecuteChangeSet'
                  - 'cloudformation:Tag*'
                  - 'cloudformation:Untag*'
                  - 'cloudformation:Describe*'
              - Sid: SSMActions
                Effect: Allow
                Resource:
                  - !Sub "arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/cdk-bootstrap/*"
                Action:
                  - 'ssm:GetParameters*'
              - Sid: LambdaActions
                Effect: Allow
                Resource:
                  - !Sub "arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:*"
                  - !Sub "arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:layer:*"
                  - !Sub "arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:event-source-mapping:*"
                  - !Sub "arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:code-signing-config:*"
                Action:
                  - 'lambda:Add*'
                  - 'lambda:Create*'
                  - 'lambda:Delete*'
                  - 'lambda:Publish*'
                  - 'lambda:Put*'
                  - 'lambda:Update*'
                  - 'lambda:Remove*'
                  - 'lambda:Tag*'
                  - 'lambda:Untag*'
              - Sid: SQSActions
                Effect: Allow
                Resource:
                  - !Sub "arn:${AWS::Partition}:sqs:${AWS::Region}:${AWS::AccountId}:*"
                Action:
                  - 'sqs:Add*'
                  - 'sqs:Create*'
                  - 'sqs:Delete*'
                  - 'sqs:Remove*'
                  - 'sqs:SeqQueueAttributes*'
                  - 'sqs:Tag*'
                  - 'sqs:Untag*'
              - Sid: S3Actions
                Effect: Allow
                Resource:
                  - !Sub "arn:${AWS::Partition}:s3:::*"
                Action:
                  - 's3:CreateBucket*'
                  - 's3:DeleteBucket*'
                  - 's3:PutBucket*'
                  - 's3:PutEncryptionConfig*'
                  - 's3:PutIntelligent*'
                  - 's3:PutRreplication*'
                  - 's3:RreplicateDelete*'
                  - 's3:RreplicateTags*'
                  - 's3:Tag*'
                  - 's3:Untag*'
              - Sid: IAMActions
                Effect: Allow
                Resource:
                  - !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:role/*"
                  - !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/*"
                Action:
                  - 'iam:AttachRolePolicy*'
                  - 'iam:CreatePolicy*'
                  - 'iam:CreateRole*'
                  - 'iam:UpdateRole*'
                  - 'iam:AttachRolePolicy*'
                  - 'iam:PutRolePolicy*'
                  - 'iam:DetachRolePolicy*'
                  - 'iam:DeletePolicy*'
                  - 'iam:DeleteRole*'
                  - 'iam:CreateServiceLinkedRole*'
                  - 'iam:DeleteServiceLinkedRole*'
                  - 'iam:CreateOpenIDConnectProvider*'
                  - 'iam:DeleteOpenIDConnectProvider*'
                  - 'iam:PutRolePermissionsBoundary*'
                  - 'iam:DeleteRolePermissionsBoundary*'
                  - 'iam:TagPolicy*'
                  - 'iam:TagRole*'
                  - 'iam:UntagPolicy*'
                  - 'iam:UntagRole*'
